export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const RESET_AUTH_STATUS = 'RESET_AUTH_STATUS';

export const RESET_CHECKOUT_STATUS = 'RESET_CHECKOUT_STATUS';

export const LOGOUT = 'LOGOUT';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';

export const START_LOADING = 'START_LOADING';

export const END_LOADING = 'END_LOADING';

export const ADD_TO_CART = 'ADD_TO_CART';

export const UPDATE_CART = 'UPDATE_CART';

export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'

export const ADD_CART_FAILURE = 'ADD_CART_FAILURE';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';