export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';

export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGIN_RESTAURANT_FAILURE = 'LOGIN_RESTAURANT_FAILURE';

export const LOGIN_RESTAURANT_SUCCESS = 'LOGIN_RESTAURANT_SUCCESS';

export const RESET_AUTH_STATUS = 'RESET_AUTH_STATUS';

export const LOGOUT = 'LOGOUT';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT'